// SPDX-License-Identifier: AGPL-3.0-or-later

/*
 * Generated by `node scripts/build-music-font.mjs`. Do not edit by hand.
 *
 * Names and codepoints from the SMuFL specification, extents from Bravura's own metadata. The
 * shipped subset covers:
 *
 * - `U+E260`–`U+E264`, accidentals
 * - `U+E1D2`–`U+E1DB`, noteheads and stemmed notes
 * - `U+E1E7`–`U+E1E7`, augmentation dot
 * - `U+E4E3`–`U+E4E7`, rests
 * - `U+E080`–`U+E09F`, time signature digits
 * - `U+ECA0`–`U+ECA9`, metronome marks
 */

/** Name of one music glyph, as SMuFL names it. */
export type MusicGlyph =
  | 'timeSig0'
  | 'timeSig1'
  | 'timeSig2'
  | 'timeSig3'
  | 'timeSig4'
  | 'timeSig5'
  | 'timeSig6'
  | 'timeSig7'
  | 'timeSig8'
  | 'timeSig9'
  | 'timeSigCommon'
  | 'timeSigCutCommon'
  | 'timeSigPlus'
  | 'timeSigPlusSmall'
  | 'timeSigFractionalSlash'
  | 'timeSigEquals'
  | 'timeSigMinus'
  | 'timeSigMultiply'
  | 'timeSigParensLeftSmall'
  | 'timeSigParensRightSmall'
  | 'timeSigParensLeft'
  | 'timeSigParensRight'
  | 'timeSigComma'
  | 'timeSigFractionQuarter'
  | 'timeSigFractionHalf'
  | 'timeSigFractionThreeQuarters'
  | 'timeSigFractionOneThird'
  | 'timeSigFractionTwoThirds'
  | 'timeSigX'
  | 'timeSigOpenPenderecki'
  | 'noteWhole'
  | 'noteHalfUp'
  | 'noteHalfDown'
  | 'noteQuarterUp'
  | 'noteQuarterDown'
  | 'note8thUp'
  | 'note8thDown'
  | 'note16thUp'
  | 'note16thDown'
  | 'note32ndUp'
  | 'augmentationDot'
  | 'accidentalFlat'
  | 'accidentalNatural'
  | 'accidentalSharp'
  | 'accidentalDoubleSharp'
  | 'accidentalDoubleFlat'
  | 'restWhole'
  | 'restHalf'
  | 'restQuarter'
  | 'rest8th'
  | 'rest16th'
  | 'metNoteDoubleWhole'
  | 'metNoteDoubleWholeSquare'
  | 'metNoteWhole'
  | 'metNoteHalfUp'
  | 'metNoteHalfDown'
  | 'metNoteQuarterUp'
  | 'metNoteQuarterDown'
  | 'metNote8thUp'
  | 'metNote8thDown'
  | 'metNote16thUp';

/**
 * The character each glyph is set with.
 *
 * @remarks SMuFL places every glyph in the private use area, so these are meaningless in any
 * other font. Always set them in a run of their own; see {@link musicMarkup}.
 */
export const MUSIC_CHARS: Readonly<Record<MusicGlyph, string>> = {
  timeSig0: '\u{E080}',
  timeSig1: '\u{E081}',
  timeSig2: '\u{E082}',
  timeSig3: '\u{E083}',
  timeSig4: '\u{E084}',
  timeSig5: '\u{E085}',
  timeSig6: '\u{E086}',
  timeSig7: '\u{E087}',
  timeSig8: '\u{E088}',
  timeSig9: '\u{E089}',
  timeSigCommon: '\u{E08A}',
  timeSigCutCommon: '\u{E08B}',
  timeSigPlus: '\u{E08C}',
  timeSigPlusSmall: '\u{E08D}',
  timeSigFractionalSlash: '\u{E08E}',
  timeSigEquals: '\u{E08F}',
  timeSigMinus: '\u{E090}',
  timeSigMultiply: '\u{E091}',
  timeSigParensLeftSmall: '\u{E092}',
  timeSigParensRightSmall: '\u{E093}',
  timeSigParensLeft: '\u{E094}',
  timeSigParensRight: '\u{E095}',
  timeSigComma: '\u{E096}',
  timeSigFractionQuarter: '\u{E097}',
  timeSigFractionHalf: '\u{E098}',
  timeSigFractionThreeQuarters: '\u{E099}',
  timeSigFractionOneThird: '\u{E09A}',
  timeSigFractionTwoThirds: '\u{E09B}',
  timeSigX: '\u{E09C}',
  timeSigOpenPenderecki: '\u{E09D}',
  noteWhole: '\u{E1D2}',
  noteHalfUp: '\u{E1D3}',
  noteHalfDown: '\u{E1D4}',
  noteQuarterUp: '\u{E1D5}',
  noteQuarterDown: '\u{E1D6}',
  note8thUp: '\u{E1D7}',
  note8thDown: '\u{E1D8}',
  note16thUp: '\u{E1D9}',
  note16thDown: '\u{E1DA}',
  note32ndUp: '\u{E1DB}',
  augmentationDot: '\u{E1E7}',
  accidentalFlat: '\u{E260}',
  accidentalNatural: '\u{E261}',
  accidentalSharp: '\u{E262}',
  accidentalDoubleSharp: '\u{E263}',
  accidentalDoubleFlat: '\u{E264}',
  restWhole: '\u{E4E3}',
  restHalf: '\u{E4E4}',
  restQuarter: '\u{E4E5}',
  rest8th: '\u{E4E6}',
  rest16th: '\u{E4E7}',
  metNoteDoubleWhole: '\u{ECA0}',
  metNoteDoubleWholeSquare: '\u{ECA1}',
  metNoteWhole: '\u{ECA2}',
  metNoteHalfUp: '\u{ECA3}',
  metNoteHalfDown: '\u{ECA4}',
  metNoteQuarterUp: '\u{ECA5}',
  metNoteQuarterDown: '\u{ECA6}',
  metNote8thUp: '\u{ECA7}',
  metNote8thDown: '\u{ECA8}',
  metNote16thUp: '\u{ECA9}',
};

/**
 * How far a glyph reaches above and below the baseline, in staff spaces.
 *
 * @remarks From Bravura's `glyphBBoxes`. A staff space is a quarter of the em, so a glyph
 * reaching 1.4 spaces above the baseline reaches 0.35em above it.
 */
export const MUSIC_EXTENTS: Readonly<Record<MusicGlyph, { north: number; south: number }>> = {
  timeSig0: { north: 1.004, south: -1 },
  timeSig1: { north: 1.004, south: -1 },
  timeSig2: { north: 1.016, south: -1.028 },
  timeSig3: { north: 0.996, south: -1.004 },
  timeSig4: { north: 1.004, south: -1 },
  timeSig5: { north: 0.984, south: -1.004 },
  timeSig6: { north: 1.004, south: -0.996 },
  timeSig7: { north: 0.996, south: -1 },
  timeSig8: { north: 1.036, south: -1.036 },
  timeSig9: { north: 1.004, south: -0.996 },
  timeSigCommon: { north: 1.004, south: -0.996 },
  timeSigCutCommon: { north: 1.444, south: -1.436 },
  timeSigPlus: { north: 1, south: -1 },
  timeSigPlusSmall: { north: 0.492, south: -0.528 },
  timeSigFractionalSlash: { north: 1, south: -1.004 },
  timeSigEquals: { north: 0.496, south: -0.5 },
  timeSigMinus: { north: 0.16, south: -0.14 },
  timeSigMultiply: { north: 0.792, south: -0.792 },
  timeSigParensLeftSmall: { north: 0.996, south: -1.004 },
  timeSigParensRightSmall: { north: 0.996, south: -1.004 },
  timeSigParensLeft: { north: 1.964, south: -1.956 },
  timeSigParensRight: { north: 1.964, south: -1.956 },
  timeSigComma: { north: 0.552, south: -0.6 },
  timeSigFractionQuarter: { north: 1.076, south: -0.992 },
  timeSigFractionHalf: { north: 1.1, south: -0.992 },
  timeSigFractionThreeQuarters: { north: 1.016, south: -1 },
  timeSigFractionOneThird: { north: 1.072, south: -1 },
  timeSigFractionTwoThirds: { north: 1.02, south: -1 },
  timeSigX: { north: 1.5, south: -1.508 },
  timeSigOpenPenderecki: { north: 1, south: -0.992 },
  noteWhole: { north: 0.544, south: -0.548 },
  noteHalfUp: { north: 3.5, south: -0.58 },
  noteHalfDown: { north: 0.58, south: -3.5 },
  noteQuarterUp: { north: 3.5, south: -0.564 },
  noteQuarterDown: { north: 0.564, south: -3.5 },
  note8thUp: { north: 3.492, south: -0.552 },
  note8thDown: { north: 0.564, south: -3.528 },
  note16thUp: { north: 3.492, south: -0.552 },
  note16thDown: { north: 0.564, south: -3.532 },
  note32ndUp: { north: 4.092, south: -0.552 },
  augmentationDot: { north: 0.2, south: -0.2 },
  accidentalFlat: { north: 1.756, south: -0.7 },
  accidentalNatural: { north: 1.364, south: -1.34 },
  accidentalSharp: { north: 1.4, south: -1.392 },
  accidentalDoubleSharp: { north: 0.508, south: -0.5 },
  accidentalDoubleFlat: { north: 1.748, south: -0.7 },
  restWhole: { north: 0.036, south: -0.54 },
  restHalf: { north: 0.568, south: -0.008 },
  restQuarter: { north: 1.492, south: -1.5 },
  rest8th: { north: 0.696, south: -1.004 },
  rest16th: { north: 0.716, south: -2 },
  metNoteDoubleWhole: { north: 0.68, south: -0.672 },
  metNoteDoubleWholeSquare: { north: 0.792, south: -0.76 },
  metNoteWhole: { north: 0.592, south: -0.5 },
  metNoteHalfUp: { north: 2.752, south: -0.564 },
  metNoteHalfDown: { north: 0.564, south: -2.752 },
  metNoteQuarterUp: { north: 2.752, south: -0.564 },
  metNoteQuarterDown: { north: 0.564, south: -2.752 },
  metNote8thUp: { north: 2.784, south: -0.564 },
  metNote8thDown: { north: 0.564, south: -2.824 },
  metNote16thUp: { north: 2.8, south: -0.564 },
};

/** Staff spaces in one em, which SMuFL fixes at four. */
export const SPACES_PER_EM = 4;

/**
 * A glyph as markup, set in its own run at its own size.
 *
 * @remarks Never let a music glyph inherit the body text's size or baseline: SMuFL draws to a
 * staff, not to a text baseline, so an accidental set inline at the label's own size sits low and
 * small. The span is sized from the em and shifted so the glyph's own centre lands on the text's
 * centre. `label` becomes the accessible name, because the codepoint reads as nothing.
 */
export function musicMarkup(glyph: MusicGlyph, label: string): string {
  const extent = MUSIC_EXTENTS[glyph];
  const centre = ((extent.north + extent.south) / 2 / SPACES_PER_EM).toFixed(3);
  return (
    `<span class="axys-smufl" role="img" aria-label="${label}" ` +
    `style="--axys-smufl-shift: ${centre}em">${MUSIC_CHARS[glyph]}</span>`
  );
}

/**
 * Sharp, flat and natural for running text.
 *
 * @remarks The ordinary Unicode musical symbols, not SMuFL. A label carrying one of these must
 * not pull a 16 KB font in behind it, and every UI face has them.
 */
export const TEXT_ACCIDENTALS = {
  sharp: '\u{266F}',
  flat: '\u{266D}',
  natural: '\u{266E}',
} as const;
