// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Generates `web/src/ui/icons.ts` from the checked-in name map.
 *
 * The generated file is committed, so a build and a test run need no network and the application
 * carries no runtime icon dependency. `lucide-static` is not a dependency of this project at all:
 * it unpacks to roughly 50MB for the fifty-odd glyphs used here, so the glyphs are fetched from
 * the CDN at the pinned version instead and only when this script is run.
 *
 * Usage: `node scripts/build-icons.mjs [--check]`. With `--check` nothing is written and the exit
 * status says whether the committed file is what the map produces.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { format, resolveConfig } from 'prettier';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const MAP = resolve(HERE, 'icon-map.json');
const OUT = resolve(HERE, '..', 'web', 'src', 'ui', 'icons.ts');

/**
 * One glyph's markup, as Lucide publishes it.
 *
 * Only the attributes that decide where it is drawn are touched: the intrinsic size is dropped so
 * the stylesheet sizes it, and the authoring class goes with it. `viewBox`, `stroke-width` and the
 * path data are left exactly as shipped, which is what gives Lucide's own sizing rule of stroke
 * width equal to size over twelve at the two sizes Axys renders.
 */
async function fetchIcon(version, name) {
  const url = `https://cdn.jsdelivr.net/npm/lucide-static@${version}/icons/${name}.svg`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`${name}: ${String(response.status)} from ${url}`);
  }
  const source = await response.text();
  return source
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+width="[^"]*"/, '')
    .replace(/\s+height="[^"]*"/, '')
    .replace(/\s+class="[^"]*"/, '')
    .replace('<svg', '<svg aria-hidden="true" focusable="false"')
    .replace(/\s+/g, ' ')
    .replace(/> </g, '><')
    .replace(/ \/>/g, '/>')
    .replace(/ >/g, '>')
    .trim();
}

function quote(text) {
  return `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function union(names) {
  return names.map((name) => `  | '${name}'`).join('\n');
}

function render(map, markup) {
  const names = Object.keys(map.icons);
  const states = Object.keys(map.states);
  const entries = names.map((name) => `  ${name}: ${quote(markup[name])},`).join('\n');
  const pairs = states
    .map((name) => `  ${name}: { on: '${map.states[name].on}', off: '${map.states[name].off}' },`)
    .join('\n');
  return `// SPDX-License-Identifier: AGPL-3.0-or-later

/*
 * Generated by \`node scripts/build-icons.mjs\` from \`scripts/icon-map.json\`. Do not edit by hand.
 *
 * The glyphs are Lucide ${map.lucide}, ISC licensed, taken unmodified but for the intrinsic size,
 * which the stylesheet supplies so one glyph serves both rendered sizes. Lucide's per-file licence
 * comment is dropped in favour of this one line and the entry in THIRD_PARTY_LICENSES.md, rather
 * than repeated once per glyph.
 */

/** Name of one glyph. */
export type IconName =
${union(names)};

/**
 * Inline SVG markup per glyph, on Lucide's 24 grid and drawn in \`currentColor\`.
 *
 * @remarks The markup is author-controlled and safe to assign with \`innerHTML\`. Size it from the
 * stylesheet: 20px in the toolbar and tool palette, 16px in menus, inspector rows and the status
 * bar, which are the only two sizes Axys renders.
 */
export const ICONS: Readonly<Record<IconName, string>> = {
${entries}
};

/** Name of one control whose glyph changes with its state. */
export type StateIconName =
${union(states)};

/** The two glyphs a state control picks between. */
export interface StateIconPair {
  /** Shown while the control is on, or while what it names is open. */
  on: IconName;
  /** Shown while the control is off, or while what it names is closed. */
  off: IconName;
}

/**
 * Glyph pair per state control.
 *
 * @remarks A toggle swaps the glyph rather than only dimming one, because a dimmed icon reads as
 * disabled. \`aria-pressed\` carries the state either way; the swap is decoration. Where Lucide
 * ships no off variant, and \`metronome\` and \`magnet\` are the two that matter here, the control
 * keeps one glyph and carries its state in its pressed styling. Never hand-draw a slashed variant:
 * a bespoke off glyph beside real Lucide pairs is immediately visible.
 */
export const STATE_ICONS: Readonly<Record<StateIconName, StateIconPair>> = {
${pairs}
};

/** Icon markup for a glyph. */
export function icon(name: IconName): string {
  return ICONS[name];
}

/** Icon markup for a state control, picked by its state. */
export function stateIcon(name: StateIconName, on: boolean): string {
  const pair = STATE_ICONS[name];
  return ICONS[on ? pair.on : pair.off];
}
`;
}

const map = JSON.parse(readFileSync(MAP, 'utf8'));
const markup = {};
for (const [name, lucide] of Object.entries(map.icons)) {
  markup[name] = await fetchIcon(map.lucide, lucide);
}
for (const [name, pair] of Object.entries(map.states)) {
  for (const side of ['on', 'off']) {
    if (!(pair[side] in map.icons)) {
      throw new Error(
        `state ${name}.${side} names ${pair[side]}, which the icon map does not hold`,
      );
    }
  }
}

// Formatted here rather than left to a later `prettier --write`, so `--check` compares the file
// against what the map produces and not against how it happens to be wrapped.
const generated = await format(render(map, markup), {
  ...(await resolveConfig(OUT)),
  filepath: OUT,
});
if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf8');
  if (current !== generated) {
    console.error('web/src/ui/icons.ts is not what scripts/icon-map.json produces.');
    process.exit(1);
  }
  console.log(`icons.ts matches the map, ${String(Object.keys(map.icons).length)} glyphs.`);
} else {
  writeFileSync(OUT, generated);
  console.log(
    `Wrote ${OUT}, ${String(Object.keys(map.icons).length)} glyphs from Lucide ${map.lucide}.`,
  );
}
